complete -c arbor -s G -l show-gitignored -d "Show files listed in .gitignore"
complete -c arbor -s H -l show-hiddens -d "Include hidden files and directories"
complete -c arbor -s c -l color -a "auto always never" -d "Color output mode"
complete -c arbor -s i -l icons -d "Add icons for known file types"
complete -c arbor -s d -l depth -d "Limit tree depth"
complete -c arbor -s g -l git -d "Display Git status indicators"
complete -c arbor -s b -l git-branch -d "Show Git branch name"
complete -c arbor -s j -l json -d "Output the tree as JSON"
complete -c arbor -s n -l count -d "Print only the number of files"
complete -c arbor -s t -l time -d "Measure execution time"
complete -c arbor -s v -l verbose -d "Enable verbose logging"
