name: release
on:
  push:
    tags: ["v*.*.*"]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            target: x86_64-unknown-linux-musl
          - os: ubuntu-latest
            target: aarch64-unknown-linux-musl
          - os: macos-latest
            target: x86_64-apple-darwin
          - os: macos-latest
            target: aarch64-apple-darwin
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}

      - name: Build
        run: cargo build --release --locked --target ${{ matrix.target }}

      - name: Strip
        run: |
          BIN=target/${{ matrix.target }}/release/stree
          if [[ "${{ runner.os }}" == "Linux" ]]; then strip "$BIN" || true; fi
          if [[ "${{ runner.os }}" == "macOS" ]]; then strip -x "$BIN" || true; fi

      - name: Package
        shell: bash
        run: |
          TAG="${GITHUB_REF_NAME}"
          PKG="stree-${TAG}-${{ matrix.target }}"
          mkdir -p pack
          cp target/${{ matrix.target }}/release/stree pack/
          cp LICENSE pack/
          tar -C pack -czf "${PKG}.tar.gz" .
          shasum -a 256 "${PKG}.tar.gz" > "${PKG}.sha256"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: stree-${{ github.ref_name }}-${{ matrix.target }}
          path: |
            stree-${{ github.ref_name }}-${{ matrix.target }}.tar.gz
            stree-${{ github.ref_name }}-${{ matrix.target }}.sha256

  release:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist
      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: dist/**/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
